<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Faker\Factory as Faker;

class GallerySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();
        $makanan = '/images/galeri/makanan/';
        $pemandangan = '/images/galeri/pemandangan/';
        $login = '/images/login/';
        $paket = '/images/galeri/paket/';

        DB::table('galleries')->insert([
            [
                'name' => 'Selamat Datang di Petung Park',
                'photo_link' => '/images/beranda/slideshow/petungpark.jpg',
                'description' => "Tempat wisata hidden place yang menawarkan pemandangan alam yang luas dan indah serta udara yang menyejukkan",
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gazebo Kecek Air',
                'photo_link' => $pemandangan . 'gazeboKecek.JPG',
                'description' => "Terdapat air di bawah gazebo yang dapat bermain air atau berkecek ria",
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Acara Pelatihan Prima',
                'photo_link' => $pemandangan . 'pelatihanPrima_3.jpg',
                'description' => "Pelatihan Pelayanan Prima diselenggarakan oleh Ubaya",
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gazebo Lesehan',
                'photo_link' => $pemandangan . 'rapatPengembanganDesaWisata.JPG',
                'description' => $faker->sentence,
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jalan Hutan Bambu',
                'photo_link' => $pemandangan . 'jalanHutanBambu.JPG',
                'description' => 'Jalur rindang dengan pepohonan bambu tinggi yang menciptakan suasana asri dan sejuk.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gazebo',
                'photo_link' => $pemandangan . 'gazeboUntukAcara.JPG',
                'description' => 'Tempat bersantai dengan pemandangan alam terbuka yang cocok untuk beristirahat setelah beraktivitas.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sumber Air',
                'photo_link' => $pemandangan . 'sumberMataAir.JPG',
                'description' => 'Aliran air alami yang jernih dan segar, menjadi daya tarik utama di sekitar kawasan wisata.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Hutan Bambu',
                'photo_link' => $pemandangan . 'pohonBambu.JPG',
                'description' => 'Wisata hutan bambu seringkali digunakan untuk foto-foto yang aesthetic.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kolam Bayi',
                'photo_link' => $pemandangan . 'kolamBayi.JPG',
                'description' => 'Kolam renang aman dengan kedalaman rendah yang dirancang khusus untuk anak-anak.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pujasera',
                'photo_link' => $pemandangan . 'pujaseraTampakLuar.jpg', // Correct concatenation
                'description' => 'Tempat makan dengan berbagai pilihan kuliner tradisional dan modern untuk pengunjung.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tempe Goreng',
                'photo_link' => $makanan . 'tempeGoreng.jpg',
                'description' => 'Tempe goreng renyah yang disajikan dengan sambal khas, cocok sebagai camilan atau lauk.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Bebek Goreng Ngos',
                'photo_link' => $makanan . 'bebekngos.JPG',
                'description' => 'Bebek goreng yang empuk dan gurih dengan bumbu tradisional, disajikan dengan sambal pedas.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pisang Coklat',
                'photo_link' => $makanan . 'pisangCoklat.jpg',
                'description' => 'Pisang coklat yang lembut dan manis dengan pelengkap seperti gula dan cokelat, cocok untuk camilan sehari-hari.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nasi Goreng',
                'photo_link' => $makanan . 'nasigorengpetung.jpg',
                'description' => 'Nasi goreng khas dengan campuran sayuran dan daging, disajikan hangat dengan pelengkap kerupuk.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Es Teh Manis',
                'photo_link' => $makanan . 'esTehManis.jpeg',
                'description' => 'Minuman segar dengan rasa teh manis yang dingin, pas untuk menghilangkan dahaga.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kentang Goreng',
                'photo_link' => $makanan . 'kentangGoreng.png',
                'description' => 'Kentang goreng renyah dengan tekstur lembut di dalam, cocok sebagai camilan atau pelengkap makanan.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Es Krim Stroberi',
                'photo_link' => $makanan . 'icecreamstraw.jpg',
                'description' => 'Es krim stroberi yang manis dan lembut, memberikan sensasi segar dengan rasa buah yang alami.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ayam Geprek',
                'photo_link' => $makanan . 'ayamsambaltrancam.jpg',
                'description' => 'Ayam goreng yang digeprek dengan sambal pedas, disajikan dengan nasi hangat dan lalapan.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Profile Picture',
                'photo_link' => $login . 'profilePic.jpg',
                'description' => 'Saya Amel sebagai admin.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kemah',
                'photo_link' => $pemandangan . 'kemah.jpg',
                'description' => 'Tidur dan bersantai sembari menikmati keindahan alam.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jalan Hutan Bambu 2',
                'photo_link' => $pemandangan . 'jalanHutanBambu_2.JPG',
                'description' => 'Jalanan Pohon Bambu yang menakjubkan.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pemandangan Sawah',
                'photo_link' => $pemandangan . 'sawah.jpg',
                'description' => 'Pemandangan alam yang akan memanjakan mata',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Es Kopi Susu',
                'photo_link' => $makanan . 'eskopisusu.jpg',
                'description' => 'Es Kopi Susu dapat dinikmati sambil menikmati udara pegunungan yang sejuk',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket Hemat 5-6 Orang',
                'photo_link' => $paket . 'hemat.png',
                'description' => 'Paket hemat untuk keluarga kecil.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Paket Super 8-10 Orang',
                'photo_link' => $paket . 'super.png',
                'description' => 'Paket Super untuk keluarga besar.',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Soft Opening Petung Park',
                'photo_link' => $pemandangan . 'softopeningpetung.jpg',
                'description' => 'Soft Opening Petung Park',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sambang Desa oleh Menteri Desa',
                'photo_link' => $pemandangan . 'sambangdesa1.jpg',
                'description' => 'Foto Bersama Bapak Menteri dengan Perangkat Desa serta pengelola Petung Park',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Atraksi Budaya Lokal',
                'photo_link' => $pemandangan . 'eventbudaya.jpg',
                'description' => 'Event Budaya Lokal terlaksana dengan sangat baik dan ramai pengunjung',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pelatihan Pelayanan Prima',
                'photo_link' => $pemandangan . 'pelatihanprima1.jpg',
                'description' => 'Trainer dari Pelatihan Pelayanan Prima adalah Bapak Hayomi',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ayam Goreng',
                'photo_link' => $makanan . 'ayamgoreng.jpg',
                'description' => 'Ayam goreng yang lezat dan disajikan dengan nasi hangat',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tahu Goreng',
                'photo_link' => $makanan . 'tahugoreng.jpg',
                'description' => 'Tahu goreng yang lezat dan empuk',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tempe Goreng',
                'photo_link' => $makanan . 'tempegoreng.jpg',
                'description' => 'Tempe Goreng yang lezat dan empuk',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tempe Goreng',
                'photo_link' => $makanan . 'tempegoreng.jpg',
                'description' => 'Tempe Goreng yang lezat dan empuk',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dr. (H.C.) Drs. H. Abdul Halim Iskandar, M.Pd',
                'photo_link' => $pemandangan . 'halimmeja.jpg',
                'description' => 'Bapak Menteri sedang berdiskusi sembari menyantap makanan dari petung park',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pelatihan Pelayanan Prima',
                'photo_link' => $pemandangan . 'pelatihanhayomi.jpg',
                'description' => 'Pengelola wisata sedang sharing pengalaman pada sesi diskusi',
                'status' => 1,
                'number_love' => $faker->numberBetween(0, 20),
                'created_at' => now(),
                'updated_at' => now(),
            ],
            
            // [
            //     'name' => 'Pelatihan Ekowisata',
            //     'photo_link' => $pemandangan . 'pelatihanekowisata.jpg',
            //     'description' => 'Pelatihan Ekowisata',
            //     'status' => 1,
            //     'number_love' => $faker->numberBetween(0, 20),
            //     'created_at' => now(),
            //     'updated_at' => now(),
            // ],
            
        ]);
    }
}
